---
title: "README"
output: 
    html_document:
        keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## LabeledPlot

This is a Shiny app to create scatterplots with several labeling options.

* Input: csv or xlsx
* Repel points and text
* Selection by names or by values
* Output: pdf - further adjustable


## Usage

* Use the online version (slower): https://tschauer.shinyapps.io/LabledPlots/
* Download the app.R file and install the required packages (see in the file)


## Examples



```{r, echo=FALSE, dpi=300, fig.align='left'}
library(png)

example1 <- readPNG("example1.png")
example2 <- readPNG("example2.png")

par(mfrow=c(1,2), mar=c(6,3,2,0), oma=c(0,0,0,0))

plot(0:1,0:1, type='n', xlab="", ylab="", xaxt="n", yaxt="n", bty="n")
rasterImage(example1, xleft = 0, ybottom = 0, xright = 1, ytop = 1)

plot(0:1,0:1, type='n', xlab="", ylab="", xaxt="n", yaxt="n", bty="n")
rasterImage(example2, xleft = 0, ybottom = 0, xright = 1, ytop = 1)


```



